eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.60.157:8761/eureka/
  instance:
    hostname: http://192.168.60.157
    
test:
  cloudValue: hello4
  
